---
abstract: "Sends emails with attachments supporting Auth over TLS or SSL (for example: Google's SMTP)."
author:
  - "Juan José 'Peco' San Martín <peco@cpan.org>"
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Send-SMTP-Gmail
no_index:
  directory:
    - t
    - inc
requires:
  Email::Date::Format: 0
  File::Spec: 0
  LWP::MediaTypes: 0
  MIME::Base64: 0
  Net::SMTP: 0
  Net::SMTPS: 0
  Net::SMTP_auth: 0
  Test::More: 0
version: 0.85
